# Generated by Django 4.0.5 on 2022-06-22 12:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('thumbnail', models.FileField(upload_to='', verbose_name='썸네일')),
                ('desc', models.TextField(verbose_name='설명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('start_view', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 21, 53, 28, 362634), verbose_name='노출시작일')),
                ('end_view', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 21, 53, 28, 362634), verbose_name='노출종료일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
