# Generated by Django 4.0.5 on 2022-06-22 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_view',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 23, 55, 55, 590937), verbose_name='노출종료일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_view',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 23, 55, 55, 590937), verbose_name='노출시작일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(upload_to='product/', verbose_name='썸네일'),
        ),
    ]
