# Generated by Django 4.0.5 on 2022-06-21 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_view',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 0, 1, 55, 810211), verbose_name='노출종료'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_view',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 0, 1, 55, 810211), verbose_name='노출시작'),
        ),
    ]
