# Generated by Django 4.0.5 on 2022-06-22 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_end_view_alter_article_start_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_view',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 21, 53, 28, 361634), verbose_name='노출종료'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_view',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 21, 53, 28, 361634), verbose_name='노출시작'),
        ),
    ]
